# Generated by Django 5.1.3 on 2024-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_category_is_active_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
